name = "Vermicomposting"
description = "Adds farmable worms to make your own compost and wormholes"
author = "Hazy Mind Interactive"
version = "1.0.0"
api_version = 6
dont_starve_compatible = true
reign_of_giants_compatible = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
forumthread = ""